In [1]:
import sys
sys.path.append('../src')

from preprocessing import preprocess
from train_test_split import get_train_test_split
from train_model import train_baseline_model

df = preprocess('../data/raw/telco_churn.csv')
X_train, X_test, y_train, y_test = get_train_test_split(df)

model = train_baseline_model(X_train, y_train)

# Quick sanity check — predict on the test set
predictions = model.predict(X_test)
print(predictions[:10])
print(y_test[:10].values)

[0 1 0 1 0 1 1 0 0 1]
[0 0 0 0 0 0 0 0 0 1]


/home/mohamedehab/Ai Projects /churn-prediction-api/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [2]:
from train_model import scale_features, train_baseline_model
X_train_scaled, X_test_scaled, scaler = scale_features(X_train, X_test)

model = train_baseline_model(X_train_scaled, y_train)

predictions = model.predict(X_test_scaled)
print(predictions[:10])
print(y_test[:10].values)

[0 1 0 1 0 1 1 0 0 1]
[0 0 0 0 0 0 0 0 0 1]


In [4]:
from evaluate import evaluate_model

evaluate_model(model, X_test_scaled, y_test)

Confusion Matrix:
[[925 110]
 [162 212]]

Classification Report:
              precision    recall  f1-score   support

    No Churn       0.85      0.89      0.87      1035
       Churn       0.66      0.57      0.61       374

    accuracy                           0.81      1409
   macro avg       0.75      0.73      0.74      1409
weighted avg       0.80      0.81      0.80      1409



In [1]:
import sys
sys.path.append('../src')

from preprocessing import preprocess
from train_test_split import get_train_test_split
from train_model import scale_features, train_baseline_model
from evaluate import evaluate_model

df = preprocess('../data/raw/telco_churn.csv')
X_train, X_test, y_train, y_test = get_train_test_split(df)
X_train_scaled, X_test_scaled, scaler = scale_features(X_train, X_test)

model = train_baseline_model(X_train_scaled, y_train)
evaluate_model(model, X_test_scaled, y_test)

Confusion Matrix:
[[749 286]
 [ 80 294]]

Classification Report:
              precision    recall  f1-score   support

    No Churn       0.90      0.72      0.80      1035
       Churn       0.51      0.79      0.62       374

    accuracy                           0.74      1409
   macro avg       0.71      0.75      0.71      1409
weighted avg       0.80      0.74      0.75      1409



In [4]:
from train_model import train_random_forest
from evaluate import evaluate_model

rf_model = train_random_forest(X_train, y_train)  # unscaled — trees don't need scaling
evaluate_model(rf_model, X_test, y_test)

Confusion Matrix:
[[788 247]
 [ 84 290]]

Classification Report:
              precision    recall  f1-score   support

    No Churn       0.90      0.76      0.83      1035
       Churn       0.54      0.78      0.64       374

    accuracy                           0.77      1409
   macro avg       0.72      0.77      0.73      1409
weighted avg       0.81      0.77      0.78      1409



In [5]:
from train_model import save_model

save_model(rf_model, '../models/churn_rf_model.pkl')

In [6]:
from train_model import load_model

loaded_model = load_model('../models/churn_rf_model.pkl')

# Sanity check: does the loaded model give the same predictions as the original?
import numpy as np
original_preds = rf_model.predict(X_test)
loaded_preds = loaded_model.predict(X_test)

print(np.array_equal(original_preds, loaded_preds))

True
